FROM node:18-alpine AS deps

WORKDIR /app

COPY package*.json ./

RUN npm ci --omit=dev

# Here the multi-stage build starts
FROM node:18-alpine

WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules

COPY . .

USER node

EXPOSE 5000

CMD ["node", "app.js"]